### ISSUE TITLE
Error: Need more than 2 values to unpack

### ISSUE THREAD

**Issue by stevethearkiv** [mzucker/page_dewarp#16]
Sorry I cannot get this to work, and there is nothing in the readme about additional values?

Cheers for any help you can give me

loaded boston_cooking_a.jpg with size 2448x3264 and resized to 490x653
Traceback (most recent call last):
  File "../page_dewarp.py", line 915, in <module>
    main()
  File "../page_dewarp.py", line 867, in main
    cinfo_list = get_contours(name, small, pagemask, 'text')
  File "../page_dewarp.py", line 450, in get_contours
    cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack

**Comment by Andry-Bal** [comment]
In earlier versions of openCV function _findContours()_ used to return 3 values (_image, contours, hierarchy_). In openCV 4 it returns two values (_contours, hierarchy_) and this is what causing the error. Just use openCV 3.

**Comment by bjornmosten** [comment]
You can also just remove the first _ on line 450, making the line 
```
contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
```
