### ISSUE TITLE
Type Error TypeError: '<' not supported between instances of 'ContourInfo' and 'ContourInfo'

### ISSUE THREAD

**Issue by Maria-Moosa** [mzucker/page_dewarp#21]
The code works fine for a some of my own images, but for a few images I get this TypeError:

Traceback (most recent call last):
  File "page_dewarp.py", line 918, in <module>
    main()
  File "page_dewarp.py", line 871, in main
    spans = assemble_spans(name, small, pagemask, cinfo_list)
  File "page_dewarp.py", line 493, in assemble_spans
    candidate_edges.sort()
TypeError: '<' not supported between instances of 'ContourInfo' and 'ContourInfo'

**Comment by Kiode** [comment]
I meet the same error when I use my own image as input.

**Comment by ethanthai2** [comment]
We will sort only the first element of the tuple. Change that line to: 

candidate_edges.sort(key=lambda x: x[0])

**Comment by lmmx** [comment]
Duplicate of https://github.com/lmmx/page-dewarp/pull/6 which was fixed the way ethanthai2 says
