### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by reagle** [mzucker/page_dewarp#22]
I tried to run this, but python 2 is deprecated, cv2 is not in pip anymore, there is opencv-python, but when I installed that and other dependences, I get errors...

```
╰─➤  page_dewarp.py example_input/boston_cooking_a.jpg
loaded boston_cooking_a.jpg with size 2448x3264 and resized to 490x653
Traceback (most recent call last):
  File "page_dewarp.py", line 1001, in <module>
    main()
  File "page_dewarp.py", line 954, in main
    cinfo_list = get_contours(name, small, pagemask, "text")
  File "page_dewarp.py", line 489, in get_contours
    mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE
ValueError: need more than 2 values to unpack
```

**Comment by Radcliffe** [comment]
Robert Sachunsky (@bertsky) has worked on converting the project to Python 3. See PR #20.

**Comment by Ganesh9100** [comment]
in the code find for _,contours,_ 
change _,contours,_ to contours,_
@reagle

**Comment by lmmx** [comment]
page-dewarp was ported to Python 3 and is now maintained at https://github.com/lmmx/page-dewarp

This repo is the original Python 2 version and the license has been kept to credit Matt for his work here 🙂
