### ISSUE TITLE
Python3 issues

### ISSUE THREAD

**Issue by cybernard** [mzucker/page_dewarp#27]
First all print statements need to be converted from print "" to print()

floating point errors here:
561 wrap values in int() due to floating point error
795 int(width...)
796 int(height....)

----
general errors which need handling

some text is white washed away

![DSC05331](https://user-images.githubusercontent.com/15042777/137648223-6cef49bc-9d5c-43a6-8d32-b20d4e87eaa1.JPG)
![z](https://user-images.githubusercontent.com/15042777/137648282-13759335-78b8-44e1-b2a9-115876ca995a.png)

Traceback (most recent call last):
  File "page_dewarp.py", line 915, in <module>
    main()
  File "page_dewarp.py", line 868, in main
    cinfo_list = get_contours(name, small, pagemask, 'text')
  File "page_dewarp.py", line 470, in get_contours
    contours_out.append(ContourInfo(contour, rect, tight_mask))
  File "page_dewarp.py", line 376, in __init__
    self.center, self.tangent = blob_mean_and_tangent(contour)
  File "page_dewarp.py", line 352, in blob_mean_and_tangent
    mean_x = moments['m10'] / area
ZeroDivisionError: float division by zero

apparently area can be 0 so we need to protect against this

  If area==0:
     area=1

Resizing the image resulted in problems for me, so I nulled it out with img=src

**Comment by rramphal** [comment]
It looks like there are already some open PRs to update the codebase: #14, #15, #20, #25 (most recent) in case they are useful to you.

**Comment by lmmx** [comment]
page-dewarp was ported to Python 3 and is now maintained at https://github.com/lmmx/page-dewarp

As you point out, this repo is the original Python 2 version 🙂
