### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by kylefoley76** [mzucker/page_dewarp#29]
Thank you for building this software but I cannot figure out how to install it.  99% of the time software comes with pip install instructions, for that 1% of the time when the software does not I have a very difficult time getting it to work.

**Comment by kylefoley76** [comment]
I downloaded the zip file and tried putting it in my site packages folder but I got the error 
import page_dewarp.py
Traceback (most recent call last):
  File "/Volumes/GoogleDrive/My Drive/laptop/documents/codes/venv3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-66e235c04c49>", line 1, in <module>
    import page_dewarp.py
  File "/Applications/PyCharm CE 3.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'page_dewarp.py'; 'page_dewarp' is not a package

I tried numerous other fixes but they did not work.

**Comment by lmmx** [comment]
For anyone reading this, page-dewarp is now maintained at https://github.com/lmmx/page-dewarp FYI, this repo is the original Python 2 version 🙂
