### ISSUE TITLE
incompatible with recent opencv versions?

### ISSUE THREAD

**Issue by jprobichaud** [mzucker/page_dewarp#9]
It's a very nice project you have here.  

I tried to run the project on ArchLinux with opencv 4 installed and with a virtualenv just for page_dewarp and I get the following error:

```
(venv) $ python page_dewarp.py example_input/boston_cooking_a.jpg 
loaded boston_cooking_a.jpg with size 2448x3264 and resized to 490x653
Traceback (most recent call last):
  File "page_dewarp.py", line 915, in <module>
    main()
  File "page_dewarp.py", line 867, in main
    cinfo_list = get_contours(name, small, pagemask, 'text')
  File "page_dewarp.py", line 450, in get_contours
    cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack
```

Any idea?

**Comment by zacniewski** [comment]
https://stackoverflow.com/questions/20851365/opencv-contours-need-more-than-2-values-to-unpack

**Comment by YagnikThanki** [comment]
Hii @jprobichaud ,
In latest opencv version findContour returns only two values instead of three so you have to modity get_contours function. Here is official document of opencv 4.0. 
**LINK**: https://docs.opencv.org/4.0.0/d3/dc0/group__imgproc__shape.html#gadf1ad6a0b82947fa1fe3c3d497f260e0

**Comment by githubization** [comment]
Got the same error, with opencv 4.0
Just to echo here: the number of output variables was changed back to 2, apparently, in opencv 4.0
I got past the error after changing the line to:

contours, hierarchy = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

("contours" is now the /first/ value)
